### ISSUE TITLE
Html => HTML

### ISSUE THREAD

**Issue by matalina** [JeffreyWay/Laravel-Testing-Decoded#11]
Fairly certain Taylor made this change to... Html to all caps HTML...

So far found it on Page 61 in Chapter 5

**Comment by JeffreyWay** [comment]
Is this a recent change in the last handful of days? The class is HtmlBuilder for me...

**Comment by matalina** [comment]
No the Facade is HTML ie: HTML::link() not Html::link()

```
                'Hash'            => 'Illuminate\Support\Facades\Hash',
        'HTML'            => 'Illuminate\Support\Facades\HTML',
        'Input'           => 'Illuminate\Support\Facades\Input',
        'Lang'            => 'Illuminate\Support\Facades\Lang',
```

**Comment by JeffreyWay** [comment]
Ahh you're right. Thanks for this.

Fixed and republished.
