### ISSUE TITLE
Calculator example

### ISSUE THREAD

**Issue by kuroi** [JeffreyWay/Laravel-Testing-Decoded#15]
@sorara in #5 does have a point. The code assumes that a $current of zero, indicates that nothing has happened before, and so

```
$this->calc->setOperands(3);
$this->calc->setOperation(new Addition);
$this->calc->calculate();
$this->calc->setOperands(2,1);
$this->calc->setOperation(new Subtraction);
$this->calc->calculate();
$this->calc->setOperands(4);
$this->calc->setOperation(new Multiplication);
$result = $this->calc->calculate();
```

would yield a result of 4 instead of zero. Nevertheless, the intended point comes across.

I'm more concerned though at the choice of test data

```
$this->calc->setOperands(3,3,3);
```

is about as bad a set of test data as is possible for this test (though that can be good for illustrative purposes as long as it's explained why it's bad!!).

Image that somebody comes along later and decides to refactor multiplication a little. However, they get it wrong and accidentally write code that repeatedly multiplies the first operand by itself instead of using the next available operand. In this case the code would be wrong, but the test would still pass.

Best practice for anything involving multiplying integers together is to use prime numbers for testing, thus avoiding the risk of getting the expected answer in the wrong way, e.g.

```
$this->calc->setOperands(2,3,5);
```

**Comment by JeffreyWay** [comment]
You're right. That was quick dummy code. Will fix and republish today. :)

**Comment by JeffreyWay** [comment]
Okay both done.

**Comment by kuroi** [comment]
Oh nice solution for the first time through test. I tip my hat to you Sir.

And lest there be any thoughts to the contrary, I'm hugely impressed by this book and although I've been testing for years, this is the book for which I've been waiting to take it to another level. There will be a hugely complimentary testimonial on its way, as soon as I've finish reading it.

**Comment by creativedutchmen** [comment]
Hmm, can you please explain why the code in #5 is correct?

To me it seems that if the following code is run:

```
$this->calc->setOperands(4);
$this->calc->setOperation(new Multiplication);
$this->calc->calculate();
$this->calc->setOperands(3);
$this->calc->setOperation(new Addition);
$result = $this->calc->calculate();
```

the result would be 7, whereas 3 is expected. (`$current` is `null`, so `4` is returned, which is then stored in `$this->result` and used for further calculations).

What am I missing?

**Comment by JeffreyWay** [comment]
Are you saying that 7 isn't returned? The result should be 7.
