### ISSUE TITLE
Picky point on page 116

### ISSUE THREAD

**Issue by kuroi** [JeffreyWay/Laravel-Testing-Decoded#17]
"The File class manages file system interactions. A MysqlDb repository persists data. An Email class prepares and sends emails. Notice how, in none of these example was the word, _and_ used."

... except that the last example does use the word _and_ - "prepares _and_ sends...".

**Comment by JeffreyWay** [comment]
haha - that's funny.

Fixed.

**Comment by kuroi** [comment]
How can you have fixed that barely a minute after I posted it? !!!

This is a man who really cares about the quality of his work :)

**Comment by JeffreyWay** [comment]
:) That's the nice thing about LeanPub. You can make edits and republish in seconds. So much better than the traditional model.

**Comment by kuroi** [comment]
Only _some_ of the credit belongs to Leanpub :)
