### ISSUE TITLE
Page 31 / assertArrayHasKey

### ISSUE THREAD

**Issue by lucadegasperi** [JeffreyWay/Laravel-Testing-Decoded#2]
in the example where assertArrayHasKey is used, the test array $family contains a 'parents' key whereas the assertion tests for a 'parent' key (without the s)

**Comment by JeffreyWay** [comment]
Fixed. Thanks, Lucas!

**Comment by lucadegasperi** [comment]
guess you have a problem with 's', since my name is without it :smile:

**Comment by JeffreyWay** [comment]
:) Yes, it seems so. Sorry, was still early when I responded.
