### ISSUE TITLE
use Mockery page 88

### ISSUE THREAD

**Issue by rodrigore** [JeffreyWay/Laravel-Testing-Decoded#20]
Jeffrey! In this moment I cannot try the code of the page 88  **class BaseModelTest**, but I see references of Mockery in the line 18 and others. Did you miss the reference at the top of the file or is not necessary? 

What I mean is this: **use Mockery**

**Comment by JeffreyWay** [comment]
It's not necessary in that case. If you wanted to alias it, then yes.

``` php
use Mockery as m;
```

But, otherwise, no need. :)
