### ISSUE TITLE
Testing Functions wording Page 54

### ISSUE THREAD

**Issue by nikush** [JeffreyWay/Laravel-Testing-Decoded#23]
The sentence in the second paragraph reads:

'To take a first step into these waters, we’ll test a helper function for a Laravel that
should generate an anchor tag for, called link_to.'

The wording around 'function for a Laravel' and 'generate an anchor tag for,' seem to be missing some words, or just need to be rephrased?

**Comment by JeffreyWay** [comment]
Thanks. Fixed!
