### ISSUE TITLE
link_to test (Chapter 5)

### ISSUE THREAD

**Issue by amykhar** [JeffreyWay/Laravel-Testing-Decoded#24]
If I name the function link_to as specified in the sample code, it throws an error when I run phpunit  PHP Fatal error:  Cannot redeclare link_to() ...

I easily got around this by using a different name in my function and my test, but you may want to modify the text in the book.

**Comment by JeffreyWay** [comment]
Yeah, that's because Laravel now includes a link_to function natively. I'll make a note of that.
