### ISSUE TITLE
"Verity" typo P85

### ISSUE THREAD

**Issue by sorora** [JeffreyWay/Laravel-Testing-Decoded#26]
Small typo on page 85 under the "Validations" heading, "verity" = "verify" I think

---

Another relatively simple way to ease into the process of testing models is to test validations. As an
example, to create a new author, a name field or property must be present. Otherwise, it’s invalid,
right? How might we **verity** that in a test?

---

**Comment by JeffreyWay** [comment]
Thanks! Fixed and republished.
