### ISSUE TITLE
Page 63 / Calculator Test example really framework-agnostic?

### ISSUE THREAD

**Issue by metalmatze** [JeffreyWay/Laravel-Testing-Decoded#29]
On page 63 you wrote that the example will be framework-agnostic.

> This section will be framework-agnostic, so, if working along, create an empty directory on your desktop, and add a CalculatorTest.php file with the first test.

But creating an empty directory, if the example would be framework-agnostic, doesn't make sense, right?
Am I getting this wrong?

**Comment by JeffreyWay** [comment]
I'm just saying that the code won't be dependent on a framework. That's why I say create an empty directory. Just a place to add a couple files...not a full framework.

**Comment by metalmatze** [comment]
Alright. I think it was my fault.
Interpreted agnostic as the opposite. Sorry ;-)
