### ISSUE TITLE
Typo's I find as I read

### ISSUE THREAD

**Issue by roggel2000** [JeffreyWay/Laravel-Testing-Decoded#35]
At page 50, last paragraph -> `rest assure` should be `rest assured`

**Comment by roggel2000** [comment]
Page 54, "Testing functions", 2nd paragraph -> `an anchor tag for` should be `an anchor tag`

**Comment by roggel2000** [comment]
Page 91, paragraph below the tip -> `sample email address` should be `same email address`

**Comment by JeffreyWay** [comment]
Thanks! Fixed all and republished.
