### ISSUE TITLE
Controller Testing with layouts - Chapter 10

### ISSUE THREAD

**Issue by neyl** [JeffreyWay/Laravel-Testing-Decoded#36]
I was pulling my hair out trying to test a controller that uses Controller Layouts i.e.
I call

```
$this->layout->content=View::make(..);
```

But this makes

```
$this->assertViewHas();
```

fail 
I now found http://stackoverflow.com/questions/16607310/laravel-controller-layout-testing
which seems to imply that to test you have to use 

```
return View::make()
```

Now, being the magician that you are, please explain if it is possible to test Controller Layouts or not.
At any event, it deserves a mention in the book whether to avoid them or how to test!

**Comment by neyl** [comment]
I now found a messy solution using `View::composer()` and posted solution on stackoverflow.com BUT I AM SURE YOU CAN DO MUCH BETTER!!!!!
I am waiting for new helper method that will handle this elegantly!!!!
EDIT: posted beginning of helper method on stackoverflow

**Comment by neyl** [comment]
Posted nice helper methods on stackoverflow.
Jeffrey - what do you say?
I think you should write another book about Testing Unit Test functions!

**Comment by JeffreyWay** [comment]
I'm not sure on this one, however, I just wouldn't use layouts. Blade extensions are better.

**Comment by rujaun** [comment]
Is there still no way to test controller layouts?
