### ISSUE TITLE
Not really a typo on page 133

### ISSUE THREAD

**Issue by roggel2000** [JeffreyWay/Laravel-Testing-Decoded#43]
Page 133, 'Calling Controller Actions', first sentence:
`If you’d prefer to instead call a controller directly, you can instead use the action method, like so:`
'Instead' twice in one sentence, maybe the second one can be omitted?

Totally up to you.

**Comment by JeffreyWay** [comment]
Changed

**Comment by roggel2000** [comment]
Not related to the typo but to the contents right after this:
I remember following one of your courses on TutsPlus (while L4 was still in beta) and I now have these three methods in my `TestCase.php`:

``` php
    public function assertViewReceives($prop, $val = null)
    {
        $response = $this->client->getResponse();
        $prop = $response->getOriginalContent()->$prop;

        if ( $val ) {
            return $this->assertEquals($val, $prop);
        }
        $this->assertTrue(!! $prop);
    }
```

,

``` php
    public function assertRequestOk()
    {
        $this->assertTrue($this->client->getResponse()->isOk());
    }
```

and

``` php
    public function assertRedirectedTo($uri)
    {
        $response = $this->client->getResponse();
        $redirectedTo = $response->headers->get('Location');

        $this->assertEquals(302, $response->getStatusCode());
        $this->assertEquals($uri, $redirectedTo);
    }
```

Are these obligatory, now that L4 is out of beta?

**Comment by JeffreyWay** [comment]
No. After I gave my presentation at Laracon, Taylor added a modified version of them to core.

**Comment by roggel2000** [comment]
Lol, my own typo... Obligatory means something completely different than what I intended; superfluous :)
