### ISSUE TITLE
Question on Repositories (chapter 10)

### ISSUE THREAD

**Issue by roggel2000** [JeffreyWay/Laravel-Testing-Decoded#45]
Having followed some of your video's on Tutsplus, in my current project I already have some repositories set up.
Now, I see in your example on page 147, that you open your repo with:

``` php
use Repositories\PostRepositoryInterface;
use Post;
```

My own repositories completely omit these `use` lines, and they work just fine.

Is this because I am still binding my repositories in my `routes.php`, and not, like you're hinting on right before these lines of code, in a service provider?

**Comment by JeffreyWay** [comment]
If the class has  a namespace, then you'd have to write `\Post` within the class, rather than `Post`.
