### ISSUE TITLE
Code error, P. 75

### ISSUE THREAD

**Issue by sorora** [JeffreyWay/Laravel-Testing-Decoded#5]
In the Multiplication class example it does a check:

// Any number times 0 is 0
if ($current === 0) return $num;

It's returning the non 0 value, when it should just return 0? Otherwise a calculation of 0 x 5 would return 5 (when 0 would be correct).

Or have I just totally missed something?

Great read either way :).

**Comment by sorora** [comment]
Never mind - I think I see why now, as the default is 0 on the $result, so if they haven't passed anything, it will be doing it against zero anyway. Sorry!

(No idea how to get rid of issues on github)

**Comment by kuroi** [comment]
@sorara

As you opened the issue, there should be a "Close" button allowing you to close it next to the green comment button at the bottom of the page.
