### ISSUE TITLE
CodeCeption chapters: WebGuy vs TestGuy vs CodeGuy

### ISSUE THREAD

**Issue by roggel2000** [JeffreyWay/Laravel-Testing-Decoded#57]
In chapter 15 your examples use the `WebGuy` class, in chapter 16 you use `TestGuy`. What's the difference between all those guys and when should you use which?

**Comment by JeffreyWay** [comment]
Those are generated dynamically by Codeception, and will be referenced automatically, based upon which suite you're running tests on.

**Comment by ajcastro** [comment]
Also, based from my understanding :
__Webguy__ is for _Acceptance Test_, a test in the level of users interacting with the application.

__TestGuy__ is for _Integration Test_, a test in the level where pieces of codes or classes are communicating to each other and produce desired results.

__CodeGuy__ is for _Unit Test_, you know unit test for sure, a test in the level of the smallest unit of code which has a single or atomic responsibility.
