### ISSUE TITLE
Possible typo in code example (testing databases)

### ISSUE THREAD

**Issue by Crinsane** [JeffreyWay/Laravel-Testing-Decoded#62]
In the chapter about testing databases, this snippet comes after a few pages:
# 

For instance, imagine that you’ve added a new migration to create an authors table with a few fields.
If using my popular Laravel 4 Generators tool34, this can be accomplished using a single command.

```
php artisan generate:migration create_posts_table --fields="name:string,email:string:unique"
```
# 

First you say "create an authors table" and the code snippet generates a posts table.

**Comment by JeffreyWay** [comment]
Thanks. Fixed!
