### ISSUE TITLE
Does "closed" for an issue denote that the book has been updated?

### ISSUE THREAD

**Issue by mapsi** [JeffreyWay/Laravel-Testing-Decoded#67]
Sorry to be a pain but I see loads of issues marked as closed but I just re-downloaded the book and some of them are still there.

I am asking as I was initially very much excited about the book but now I'm getting a bit frustrated with things not working. :(

Many thanks in advance!

**Comment by JeffreyWay** [comment]
Can you give me an example of what's not working?

**Comment by mapsi** [comment]
Issue https://github.com/JeffreyWay/Laravel-Testing-Decoded/issues/25#issuecomment-18782929 for instance is still not in the book. (I just re-downloaded from the Leanpub link).

But currently I'm actually stuck with something similar to this http://stackoverflow.com/questions/17008637/mocking-eloquent-models-with-find which I ran into in chapter 11, p145: $posts = $this->post->all(); (with a mocked Post). 
But this latter is a different issue I'm still investigating. The original question was if the book has (or should have) been updated with the closed issues.

Cheers

**Comment by JeffreyWay** [comment]
Just responded to his question on StackOverflow. He mocked it incorrectly. Not an issue with the book.

**Comment by mapsi** [comment]
Thank you very much for the quick turnaround for the "secondary" issue and sorry for being a pain but the original question is still unanswered: Have the closed issues been "merged" back to the book? Cheers!

**Comment by JeffreyWay** [comment]
Most of them have been, yes.

**Comment by mapsi** [comment]
Ok, If you say so. Thanks anyway. The book is great and I love the tutorials on tutsplus. Cheers
