### ISSUE TITLE
composer.json mistake - Page 24

### ISSUE THREAD

**Issue by mdavis1982** [JeffreyWay/Laravel-Testing-Decoded#70]
On Page 24, is says to list PHPUnit in a "require-dev" section in composer.json, but the example code lists it in a normal "require" block.

**Comment by JeffreyWay** [comment]
It's difficult to determine where that is, because page 24 is different for all formats and text sizes.

Can you paste a nearby sentence where the error is?

**Comment by mdavis1982** [comment]
Sorry, Jeffrey... I was reading the PDF version.

It's in the Making Packages Available Globally section in Chapter 2, right after "To allow for this, within your computer’s home directory (or anywhere, really), create a new folder, composer-packages, add its companion composer.json file, and list your desired global dependencies within the require-dev object."

**Comment by JeffreyWay** [comment]
Thanks. Fixed!
