### ISSUE TITLE
Using array literal in the "Contributing to Laravel" section

### ISSUE THREAD

**Issue by jasonlewis** [JeffreyWay/Laravel-Testing-Decoded#71]
On page 89, the production code for `selectMonth` makes use of the literal array syntax when you've mentioned that `array()` should be used as Laravel still supports 5.3.

Offending line:

``` php
$months = [];
```

So far a solid book Jeffrey! Time to keep reading...

**Comment by JeffreyWay** [comment]
Yep. Fixed. Thanks!
