### ISSUE TITLE
Question about page 54

### ISSUE THREAD

**Issue by rydurham** [JeffreyWay/Laravel-Testing-Decoded#75]
I have a question regarding page 54: 

```
$expect = "<a href='http://:/dogs/1'>Show Dog</a>";
```

You mention that we don't want to search for "localhost:8000" when running command line tests, but when phpunit runs link_to() using laravel's url() helper, "localhost" is inserted as part of the domain. When I run the test it fails

```
1) PracticeTest::testGeneratesAnchorTag
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<a href='http://:/dogs/1'>Show Dog</a>'
+'<a href='http://localhost/dogs/1'>Show Dog</a>'
```

What am I missing? 

Thanks for your time!
~Ryan

----- PracticeTest.php

``` php
class PracticeTest extends TestCase {

    public function testGeneratesAnchorTag()
    {
        $actual = ltd_link_to('dogs/1', 'Show Dog');
        $expect = "<a href='http://:/dogs/1'>Show Dog</a>";

        $this->assertEquals($expect, $actual);
    }

}
```

----- helpers.php

``` php
function ltd_link_to($url, $body)
{
    $url = url($url);
    return "<a href='{$url}'>{$body}</a>";  
}
```

**Comment by tolgamorf** [comment]
I also encountered the same behavior. What's more, we cannot name the function as `link_to()` since it is already declared in `vendor/laravel/framework/src/Illuminate/Support/helpers.php`.

**Comment by JeffreyWay** [comment]
Yeah, it's because Taylor added that link_to helper that was covered in that chapter. I'll change the function name in the book right now so that it doesn't clash with Laravel's version.

**Comment by rydurham** [comment]
What about the use of the native url() function at the bottom of page 59?  It is returning a url that includes the TLD and the test is expecting only 'http://:/dogs/1' which for me causes the test to fail, even though you say it should pass.  I feel like I have missed something, but I don't know what it could be.  Any thoughts?

```
There was 1 failure:

1) PracticeTest::testGeneratesAnchorTag
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<a href='http://:/dogs/1'>Show Dog</a>'
+'<a href='http://localhost/dogs/1'>Show Dog</a>'

C:\wamp\www\tddlesson\app\tests\PracticeTest.php:10
C:\wamp\composer-packages\vendor\phpunit\phpunit\PHPUnit\TextUI\Command.php:176
C:\wamp\composer-packages\vendor\phpunit\phpunit\PHPUnit\TextUI\Command.php:129
```

**Comment by develpr** [comment]
+1 - same question. This actually slightly complicates things, because I ask myself "Given that I'm not supposed to be using external classes/libraries/etc within my tests, how am I supposed to know what I should assert, given Laravel's url() helper function seems to be doing it's best to guess my domain?"
