### ISSUE TITLE
Testing eloquent implementation of repository interfaces

### ISSUE THREAD

**Issue by metalmatze** [JeffreyWay/Laravel-Testing-Decoded#76]
Hey,

in chapter 11 'Testing Controllers' you refer to programming with repositories for easier controller testing.
This seems like a really good practice. But in the end I'd have to test those as well, right?

I just can't figure out how to mock eloquent to test my implementation. It always tries to hit the database...

Thanks!

**Comment by JeffreyWay** [comment]
You could inject the Eloquent model into the repository through the constructor. Still, though, mocking Eloquent models is tough, as I note in the book.

Eloquent is already highly tested, so you don't have to worry too much about that side of the testing equation. You could instead write an integration test to ensure that things are working properly.

**Comment by metalmatze** [comment]
So you think it's overrated to test the implementation of an interface as well?

I would like to test if eloquent was triggered with the correct parameters.
Because that's something that could break if wrong modified... :-/

**Comment by JeffreyWay** [comment]
No - saying that testing Eloquent is very difficult. But, luckily, Eloquent is already highly tested. So you mostly just need an integration test to make sure that it does what you expect.
