### ISSUE TITLE
Page 12 - minor mistake

### ISSUE THREAD

**Issue by GeorgeStrakhov** [JeffreyWay/Laravel-Testing-Decoded#77]
And, and, and part. The bottom of the page.

You say:
Notice how, in none of the examples above did the word, and, occur. This makes them considerably easier to test, as you’re not forced to juggle multiple objects.

But in fact a few lines earlier you have:
A TwitterStream class fetches _and_ returns tweets from the Twitter API, when given a username.

**Comment by JeffreyWay** [comment]
This was fixed a while ago, but I forgot to republish! :)

Thanks for the reminder.
