### ISSUE TITLE
Terminology Technicality

### ISSUE THREAD

**Issue by funkywaddle** [JeffreyWay/Laravel-Testing-Decoded#80]
On page 48, you declare a function:

```
public function testFetchesItemsInArrayUntilKey()
```

and on the next page, you have a code comment:

```
// When I call the until function and
// specify a different key
```

I know your point is getting across, but technically, aren't you searching through the array values, not the keys?

**Comment by JeffreyWay** [comment]
Yep. Fixed.

Thx
