### ISSUE TITLE
A bunch of small corrections

### ISSUE THREAD

**Issue by alexrussell** [JeffreyWay/Laravel-Testing-Decoded#84]
Sorry if some have already been mentioned by other people. Only just remembered you had this issue tracker after I wrote them all down.
- Page 62: "A simple `composer install` and `composer dump` should add this file to the autoloader." ⟶ "A simple `composer install` and `composer dump-autoload` should add this file to the autoloader." (Right?)
- Page 115: 'Continuing with the example from the previous "_Dilemma_ section, this time' (Not sure about this: is "Dilemma" supposed to be italic, enclosed in double quotes or what?)
- Page 119: The page mentions that `zeroOrMoreTimes()` is the default state of `shouldReceive()`, but the second code block suggests (to me) that the default is `withAnyArgs()->once()` - is this an error?
- Page 124: "Notice how, in none of these example was the word, _and_ used." ⟶ "Notice how, in none of these examples, was the word _and_ used." (Pluralise "example", reorder commas.)
- Page 129 (Lower code sample): You only call `migrate` rather than `migrate:refresh` - is this because for SQLite the database is always fresh so you only need to migrate rather than roll back and re-migrate, or is this a brain-typo? Just thought I'd check, because reading the book you say you should always `migrate:refresh` but then go on to only `migrate` when using SQLite in memory without explaining why (hence I don't know if it's an error or if it's there for a reason).
- Page 143: The reference to the chapter on Mockery appears to be copied from a web-based tutorial, and the general sentence, while valid, should probably be adapted for the book. Maybe convert the sentence from "Please review that chapter from my book, if you’re not yet familiar with it." to "Please review that chapter if you’re not yet familiar with it."
- Page 155: In the composer.json example, the best practice is to suffix your namespace with a \ (and, because it's in JSON it's a '\') so that the matcher doesn't accidentally match another namespace that _happens_ to begin with 'Way': http://getcomposer.org/doc/04-schema.md#psr-0
- Page 224: "As we reviewed earlier in this book" feels a bit robotic - maybe say which chapter?
- Page 233: The code for the view says it should be located at `app/views/sessions/new.blade.php`, but the code for the rout has `View::make('sessions.create');`
- Page 242: "With a single line of code, we can peak into the database" ⟶ "With a single line of code, we can peek into the database" (correct "peak" to "peek")
- Page 260: "A **Partial Mocks** is useful" ⟶ "A **Partial Mock** is useful"

**Comment by JeffreyWay** [comment]
Page 62: It's a native alias. Both are acceptable.
Page 115: Fine as is.
Page 119: That was referring to the with() method. Will clarify.
Page 129: Right. The DB will be fresh each time.
Page 143: Fixed.
Page 224: It's covered in multiple places in the book.
Page 233: Fixed.
Page 242: Fixed
Page 260: Fixed

Thanks for these!

**Comment by alexrussell** [comment]
No problem, but page 115 you say fine as is. I still think something's wrong - maybe I'm going crazy and don't know something but here's how it renders in the PDF:

![page 115](https://f.cloud.github.com/assets/412784/913504/931cc994-fe19-11e2-95a7-4c826cbd67b6.png)

Is it really supposed to be italic with a starting double quote and no ending double quote? Maybe that's a thing I just don't know about. If so, sorry to press you no it!

Page 62 is interesting - the command line help for composer doesn't list it as being doable - just `composer dump-autoload` and `composer dumpautoload`. Weird it doesn't have that third option.
