### ISSUE TITLE
Use of URL() helper on page 59

### ISSUE THREAD

**Issue by rydurham** [JeffreyWay/Laravel-Testing-Decoded#86]
I am still having trouble with the test being done on page 59. 

You specify that the link_to function should contain this code: 

```
$url = url($url);
return "<a href='{$url}'>{$body}</a>";
```

but the native `url()` function is inserting 'localhost' into the returned url.   This causes the test to fail, because the test is expecting only 'http://:/dogs/1'.   I feel like I am missing something obvious, but I can't figure out what it is. 

```
There was 1 failure:

1) PracticeTest::testGeneratesAnchorTag
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<a href='http://:/dogs/1'>Show Dog</a>'
+'<a href='http://localhost/dogs/1'>Show Dog</a>'
```

**Comment by timwax** [comment]
same issue as @rydurham on page 59

_suggest_

`$expect = "|<a href='http://.*/dogs/1'>Show Dog</a>|";
$this->assertRegExp($expect, $actual);`

**Comment by echochamber** [comment]
Same issue here as well. Did same thing as tim with slightly different regex "|href='http://([0-9a-zA-Z:]+)/dogs/1'\s+class=\"button\">Show Dog|"
